name: node

on:
  workflow_dispatch: # lets you run a build from the UI
  push:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: node-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20]

    runs-on: ${{ matrix.os }}

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: yarn.lock

    - name: Install
      run: yarn install

    - name: Build
      run: yarn build

    # - name: Test
    #   run: yarn test
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: '${{ github.workspace }}/dist'

    - name: Download Artifact
      uses: actions/download-artifact@v4
